name: Go
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: GOOS=windows GOARCH=amd64 go get -v -t -d ./...

    - name: Build
      run: GOOS=windows GOARCH=amd64 go build -v -o Switchcord.exe .
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Switchcord-win-x64
        path: Switchcord.exe
